#pragma once

#include <iostream>
#include <unordered_map>
#include <algorithm>
#include <fstream>
#include <thread>
#include <mutex>
#include <condition_variable>

#include "vec.h"

enum piece {
	PIECE_NONE,
	PIECE_I,
	PIECE_J,
	PIECE_L,
	PIECE_T,
	PIECE_Z,
	PIECE_S,
	PIECE_O
};

enum move {
	MOVE_LEFT,
	MOVE_RIGHT,
	MOVE_DOWN,
	MOVE_CW,
	MOVE_CCW
};

enum lock_data {
	LOCK_NONE,
	LOCK_BURN_1,
	LOCK_BURN_2,
	LOCK_BURN_3,
	LOCK_TETRIS,
	LOCK_PC,
	LOCK_TSPIN_1,
	LOCK_TSPIN_2,
	LOCK_TSPIN_3
};

struct path_data {
	piece type;
	bool is_hold;
	bool is_soft_drop;
	int index;

	void set(int other) {
		is_hold = (other & 0b1) == 0b1;
		is_soft_drop = (other & 0b10) == 0b10;
		type = (piece)((other & 0b11100) >> 2);
		index = (other >> 5) & 0b11111111;
	}
};

struct weight {
	int top_height = -32;
	int top_height_top_half = -150;
	int top_height_top_quarter = -611;
	int bumpiness = -34;
	int bumpiness_s = -8;
	int well = 60;
	int hole = -272;
	int blocked_cell = -77;
	int block_above_hole = -47;
	int block_above_hole_s = -1;
	int well_1_10 = 24;
	int well_2_9 = 20;
	int well_3_8 = 15;
	int well_center = 60;
	int structure[3] = { 298, 492, 527 };
	int b2b_max_chain = 204;
	int ren_max_chain = 119;
	int b2b_clear = 104;
	int ren_clear = 12;
	int line_sent = 101;
	int perfect_clear = 9999;
	int t_spin_1 = -57;
	int t_spin_2 = 435;
	int t_spin_3 = 708;
	int tetris = 410;
	int burn_1 = -295;
	int burn_2 = -237;
	int burn_3 = -128;
	int waste_time = -255;
	int waste_structure[3] = { -215, -155, -205 };
	int waste_T = -302;
	int waste_I = -27;
	int hold_T = 42;
	int hold_I = 53;
};

static std::unordered_map<piece, std::vector<std::vector<move>>> path_hd{
	{PIECE_O, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_DOWN },
		{MOVE_DOWN },
		{MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN }
	}},
	{PIECE_I, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_DOWN },
		{MOVE_DOWN },
		{MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN }
	}},
	{PIECE_T, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_DOWN },
		{MOVE_DOWN },
		{MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN }
	}},
	{PIECE_J, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_DOWN },
		{MOVE_DOWN },
		{MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN }
	}},
	{PIECE_L, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_DOWN },
		{MOVE_DOWN },
		{MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CCW, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN }
	}},
	{PIECE_S, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_DOWN },
		{MOVE_DOWN },
		{MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN }
	}},
	{PIECE_Z, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_LEFT, MOVE_DOWN },
		{MOVE_DOWN },
		{MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN },
		{MOVE_CW, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN },
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN }

	}}
};

static std::unordered_map<piece, std::vector<std::vector<move>>> path_sd{
	{PIECE_O, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},

		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN}
	}},
	{PIECE_I, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},

		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN}
	}},
	{PIECE_T, {
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},

		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_CCW, MOVE_DOWN},
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_CCW, MOVE_DOWN},
		{MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_CCW, MOVE_DOWN},
		{MOVE_DOWN, MOVE_RIGHT, MOVE_CCW, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_CCW, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_CCW, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_CCW, MOVE_DOWN},

		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_CW, MOVE_DOWN},
		{MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_CW, MOVE_DOWN},
		{MOVE_DOWN, MOVE_LEFT, MOVE_CW, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_CW, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_CW, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_CW, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_CW, MOVE_DOWN},

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_DOWN, MOVE_CCW, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_CCW, MOVE_DOWN},

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_DOWN, MOVE_CW, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_CW, MOVE_DOWN}
	}},
	{PIECE_J, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_DOWN, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN},

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_CCW, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_DOWN},

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN}
	}},
	{PIECE_L, {
		{MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN},
		{MOVE_LEFT, MOVE_DOWN, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN},
		{MOVE_DOWN, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN},
		{MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN},

		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_CW, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_RIGHT, MOVE_DOWN},

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN}
	}},
	{PIECE_S, {
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN}
	}},
	{PIECE_Z, {
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_LEFT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},
		{MOVE_CW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CW, MOVE_DOWN},

		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_LEFT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN},
		{MOVE_CCW, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_RIGHT, MOVE_DOWN, MOVE_CCW, MOVE_DOWN}
	}}
};

static std::unordered_map<piece, std::vector<uint16_t>> piece_form{
	{PIECE_I, {
	0b0000111100000000,
	0b0010001000100010,
	0b0000000011110000,
	0b0100010001000100
	}},
	{PIECE_J, {
	0b1000111000000000,
	0b0110010001000000,
	0b0000111000100000,
	0b0100010011000000
	}},
	{PIECE_L, {
	0b0010111000000000,
	0b0100010001100000,
	0b0000111010000000,
	0b1100010001000000
	}},
	{PIECE_S, {
	0b0110110000000000,
	0b0100011000100000,
	0b0000011011000000,
	0b1000110001000000
	}},
	{PIECE_T, {
	0b0100111000000000,
	0b0100011001000000,
	0b0000111001000000,
	0b0100110001000000
	}},
	{PIECE_Z, {
	0b1100011000000000,
	0b0010011001000000,
	0b0000110001100000,
	0b0100110010000000
	}},
	{PIECE_O, {
	0b1100110000000000
	}}
};

static std::unordered_map<piece, int> piece_init_pos{
	{PIECE_I, 3},
	{PIECE_J, 3},
	{PIECE_L, 3},
	{PIECE_S, 3},
	{PIECE_T, 3},
	{PIECE_Z, 3},
	{PIECE_O, 4}
};

static std::unordered_map<piece, std::vector<std::vector<std::vector<int>>>> piece_srs{
	{PIECE_I, {
	{{ -2, 0 }, { 1, 0 }, { -2, 1 }, { 1, -2 }},
	{{ 2, 0 }, { -1, 0 }, { 2, -1 }, { -1, 2 }},
	{{ -1, 0 }, { 2, 0 }, { -1, -2 }, { 2, 1 }},
	{{ 1, 0 }, { -2, 0 }, { 1, 2 }, { -2, -1 }}
	}},
	{PIECE_J, {
	{{ -1, 0 }, { -1, -1 }, { 0, 2 }, { -1, 2 }},
	{{ 1, 0 }, { 1, 1 }, { 0, -2 }, { 1, -2 }},
	{{ 1, 0 }, { 1, -1 }, { 0, 2 }, { 1, 2 }},
	{{ -1, 0 }, { -1, 1 }, { 0, -2 }, { -1, -2 }}
	}},
	{PIECE_L, {
	{{ -1, 0 }, { -1, -1 }, { 0, 2 }, { -1, 2 }},
	{{ 1, 0 }, { 1, 1 }, { 0, -2 }, { 1, -2 }},
	{{ 1, 0 }, { 1, -1 }, { 0, 2 }, { 1, 2 }},
	{{ -1, 0 }, { -1, 1 }, { 0, -2 }, { -1, -2 }}
	}},
	{PIECE_S, {
	{{ -1, 0 }, { -1, -1 }, { 0, 2 }, { -1, 2 }},
	{{ 1, 0 }, { 1, 1 }, { 0, -2 }, { 1, -2 }},
	{{ 1, 0 }, { 1, -1 }, { 0, 2 }, { 1, 2 }},
	{{ -1, 0 }, { -1, 1 }, { 0, -2 }, { -1, -2 }}
	}},
	{PIECE_T, {
	{{ -1, 0 }, { -1, -1 }, { 0, 2 }, { -1, 2 }},
	{{ 1, 0 }, { 1, 1 }, { 0, -2 }, { 1, -2 }},
	{{ 1, 0 }, { 1, -1 }, { 0, 2 }, { 1, 2 }},
	{{ -1, 0 }, { -1, 1 }, { 0, -2 }, { -1, -2 }}
	}},
	{PIECE_Z, {
	{{ -1, 0 }, { -1, -1 }, { 0, 2 }, { -1, 2 }},
	{{ 1, 0 }, { 1, 1 }, { 0, -2 }, { 1, -2 }},
	{{ 1, 0 }, { 1, -1 }, { 0, 2 }, { 1, 2 }},
	{{ -1, 0 }, { -1, 1 }, { 0, -2 }, { -1, -2 }}
	}},
	{PIECE_O, { { {} } }}
};